### ISSUE TITLE
Vanishing details while making changes in event submission form.

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager#1149]
If you enter a non-numeric field in a numeric field, an error message will be displayed after submitting the form and the values ​​in all fields will disappear.

If the email address is not in the correct format, an error message will be displayed after submitting the form and the values ​​in all fields will disappear.

Can you understand the error you are experiencing?
This is an error message prepared by the plugin, so you can probably understand it.

While subbitting a event form, if there is any error in respect to non entered field or wrong entry of field, The details vanishes, rather it should stay.

**Comment by ashokdudhat** [comment]
@mistry-jignesh pls ask to Priya.. why she closed before this issue.

**Comment by mistry-jignesh** [comment]
Client is facing this issue still ?
Please informed the status about issue .
So I can change status @Priya-Goenka

**Comment by mistry-jignesh** [comment]
We have checked this issue . Now this issue is not reproduced and working fine.

While subbitting a event form, if there is any error in respect to non entered field or wrong entry of field, 

The details is not  vanishes. 

Details are display properly on the page. So after verified this issue .

Now closed the issue.
