### ISSUE TITLE
Event expiry date not change after event end date.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#1249]
The event expiry date not change after the event end date. After the expiration event, when I edit the event end date, the event expiry date should automatically change as the event end date.

**Comment by ritakikani** [comment]
Admin can only add/edit event expiry date. 
As per our plugin functionality, when user create event from frontend side, then he can not able to set event expiry date, that time event expiry date will automatically set as per event end date. so the end date and expiry date will always same while post/update event from front end side.

If admin add/update event from admin side, but here admin has rights to set event expiry date as per his choice.
Because in some case user wants expiry date different from event end date.

**Comment by kinjal6810** [comment]
As the above discussion with Krinay . Admin can only add/edit event expiry date.
 so I close it.
