### ISSUE TITLE
Event Title at bottom of event detail page

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#131]
Why event title is showing at bottom of each event detail page? Is it like that or? If yes, then why?

![eventtitle](https://user-images.githubusercontent.com/49863477/63465829-54335480-c462-11e9-8ea9-ab7508ff4aa6.png)

**Comment by ritakikani** [comment]
we can use filter for remove title from theme :

`/**
 * This function will remove the post title from the single event page
 * @since 3.1.9
 * @param 
 */
add_filter( 'the_title', 'remove_single_event_listing_titles', 10, 2);
function remove_single_event_listing_titles( $title, $id = null ) {
        $post = get_post( $id );
        if ( $post->post_type == 'event_listing') {
            return '';
        }
    return $title;
}`
