### ISSUE TITLE
Form conditions

### ISSUE THREAD

**Issue by josaur** [wpeventmanager/wp-event-manager#1318]
Right now its possible to create custom fields in the event-submit form. It would be great to add optional conditions for this fields. So that an specific field is only shown if an defined option is selected in another.

**Comment by ritakikani** [comment]
Hi @josaur , 

Using field editor, you can add/edit/delete any field related to events/organizer/venue, this is only work of field editor, So we can not put specific condition for any field for specific user because this used by globally.
But of-course you can customize it easily with hook, filters and javascript/jQuery.

Thank you.
