### ISSUE TITLE
Sign In Functionality

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager#141]
Please read issues mentioned in this attached screenshot.

![sign in](https://user-images.githubusercontent.com/49863477/64819896-9a865a00-d5af-11e9-85bd-8117d17f0889.png)

**Comment by ritakikani** [comment]
1. Change message for password if password field enable at event submission time to create account then hide " You will receive your password shortly in your email. "
2. It is "Sign in" button if user have account then he need to login first otherwise new account will be created if he enter Username, Password in submit form.
For link of "Sign in" you need to set from admin side, Event Listings-> Settings -> Page -> Login Page URL.
If not set login url in settings then it will take wordpress default login page as "Sign in" page.
