### ISSUE TITLE
Code improvement

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager#1621]
Code improvement issue for version 3.1.42

**Comment by ritakikani** [comment]
Your code is correct, but it can be simplified.
The isset() function checks if a variable is set and is not null. In this case, you want to check if $field['visibility'] is set and is either equal to 1 or true. Instead of using isset() twice, you can use a single isset() and then check the value directly. 

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/155473d7-81c5-4965-9f3f-515ef01a0d0b)

We can write code like :  

if (isset($field['visibility']) && ($field['visibility'] == 1 || $field['visibility'] == true)) {
    // code here
}

This checks if $field['visibility'] is set and has a value of either 1 or true. The isset() function alone is sufficient for checking if the variable is set.

**Comment by ritakikani** [comment]
In this issue, mention that by default it should be selected,

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/7f27397a-316b-476d-b7f6-1c82a861420a)

But, it is not.

![image](https://github.com/wpeventmanager/wp-event-manager/assets/25837982/341b5db7-7396-4dbb-9169-b5556f4adf88)

And, As per me, this setting should be after "Delete Data On Uninstall" not at the end of all settings.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
It is working fine. So I closed the issue.
