### ISSUE TITLE
Add an "UPLOAD Event thumbnail" to Add/Edit Event Page - to remove the BOTTLENECK

### ISSUE THREAD

**Issue by paulpreibisch** [wpeventmanager/wp-event-manager#1654]
In add/edit event, please add a field to upload a thumbnail for the event, or better yet, automatically generate a thumbnail.
The problem is, the event listing uses the event banner for the thumbnail, and thus, the event listing is VERY SLOW because the FULL image needs to be loaded.  

SOLUTION:
allow users to upload their own event thumbnail in the add/edit events so that the event listing can be optimized.

VIDEO HERE: https://youtu.be/9VtJ9E-qICU

**Comment by RHSRSK** [comment]
There are two setting field for thumbnail
1) In Event Submission setting : When this field is checked one event thumbnail field is available in Post an Event form and we can add the thumbnail to that event.

![image](https://github.com/user-attachments/assets/451baba7-b923-43cc-b1d9-5fa1f6c84a5d)

2) In Event Listing settings : Using this setting If it is checked then thumbnail is used in event listing and if thumbnail is not it will display default image as thumbnail.

![image](https://github.com/user-attachments/assets/11a66d5f-4c67-4bec-98be-37e0022d5bd6)

**Comment by mistry-jignesh** [comment]
I have checked the issue. 
First I have enabled both options.
Added custom thumbnail image.
It is working fine.
Now I have disabled both options from the backend side the still custom thumbnail is displayed.
So Need to check it.

**Comment by RHSRSK** [comment]
This is working fine as per requirement.
1) Setting is enable: When thumbnail is available it's always display thumbnail otherwise it's show default image.
2) Setting is disable : If thumbnail is available in event it's always show thumbnail but when thumbnail is not available it's set banner image.

**Comment by mistry-jignesh** [comment]
As per @RHSRSK  :  

This is working fine as per requirement.

1. Setting is enable: When thumbnail is available it's always display thumbnail otherwise it's show default image.
2. Setting is disable : If thumbnail is available in event it's always show thumbnail but when thumbnail is not available it's set banner image. 

So I closed the issue.
