### ISSUE TITLE
new event not showing on events page

### ISSUE THREAD

**Issue by khattoumehdi** [wpeventmanager/wp-event-manager#464]
My problem is that when i add new event directly from phpmyadmin i dont find it on the event page. I can find it in the event dashbord page, i can also visit the event page by its permalink but i cant find it listed with other events added by the plugin.

**Comment by hiteshmakvana** [comment]
@khattoumehdi 
You are adding events directly from phpmyadmin will not work because we are storing events in wordpress as custom post type. I would request you to use migration plugin instead of doing directly database insertion.


You don't need to do via database that's why we are working on more features of frotnend and backend. 
https://wordpress.org/plugins/wp-event-manager-migration/


Thank you

**Comment by mistry-jignesh** [comment]
As per the above comment: You are adding events directly from phpmyadmin will not work because we are storing events in WordPress as a custom post type. I would request you to use migration plugin instead of doing directly database insertion.

You don't need to do via a database that's why we are working on more features of front end and backend.
https://wordpress.org/plugins/wp-event-manager-migration/

So I closed the issue.
