### ISSUE TITLE
Need to fix multi select type and category setting issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#625]
Right now we are providing the Multi-select Event Types and Category setting but it is not useful as much as with field editor. 

For example, if the user selects the settings for multi-select event and category and from field editor, they have select term select type for the category and type then it's a conflict with the field editor.

So we should remove the setting because it will create confusion for the user.

![image](https://user-images.githubusercontent.com/35419531/98534431-4faab580-2239-11eb-9b2e-41b9265f4b36.png)

**Comment by hiteshmakvana** [comment]
We can remove these settings due to conflicting with the field editor. 

Reason of removal: If the user trying to change the settings by enabling or disabling the mulple select then it won't allow by field editor. Field editor stored in an array and it will be complex and not user-friendly sync between setting and field editor. There should be only one way to make the multi selectable fields using field editor.

**Comment by krinaydhanani** [comment]
@Priya-Goenka Please update this thing from the doc and @siddharthgotawala Please make a new screenshot and update the site as well.

**Comment by Priya-Goenka** [comment]
@siddhart when screenshots done let me know.
