### ISSUE TITLE
Add Group field option in field editor

### ISSUE THREAD

**Issue by wpem-kishan** [wpeventmanager/wp-event-manager#698]
Add Group field option in field editor

**Comment by krinaydhanani** [comment]
Add Group field option not working in the field editor. I can see below notice and debug was generated.

![image](https://user-images.githubusercontent.com/35419531/102895344-860b5f80-448a-11eb-9fe5-a5038167c871.png)

[debug.log](https://github.com/wpeventmanager/wp-event-manager/files/5730140/debug.log)

**Comment by krinaydhanani** [comment]
To reproduce this bug please follow the staples.

Go to the field editor 
Add the Group field
Then save the field editor.

**Comment by krinaydhanani** [comment]
Still, this issue is not fixed. The below log will create while adding the group field please fixed it before then I can test further.

To reproduce this bug please follow the below steps.

First of all, make debug lof true in the config file.

Go to the dashboard on the admin side.
Click on event manager
Go to the field editor
Add the Group field ( Add all the field types).

**Check the debug log file which is generate in the content folder.**

[debug.log](https://github.com/wpeventmanager/wp-event-manager/files/5733834/debug.log)

**Comment by krinaydhanani** [comment]
If it does not reproduce in your setup then please check it on my setup. I will show you how its product. 

[debug.log](https://github.com/wpeventmanager/wp-event-manager/files/6067960/debug.log)
