### ISSUE TITLE
Event Edit Page

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#70]
If we are adding random numbers in date fields while submitting the event, it is showing date like in the screenshot on the edit event page.

![editpreview](https://user-images.githubusercontent.com/35419531/56412300-49449980-62a1-11e9-9655-651fe786c1df.png)

**Comment by hiteshmakvana** [comment]
This will happen wen you add random number or anything manually in the input box of the date picker then it will try to convert date as date format.

This will fail and store date as 1970-01-01 in this case if user wants to set restriction then they have to [override template file](https://www.wp-eventmanager.com/template-files-override) for date field to theme side and add `readyonly="true"` inside date input.

This will make more sense instead of setting default restriction form plugin.
