### ISSUE TITLE
Event Detail Page - Date Format

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager#72]
User should not be able to add random numbers and characters in date fields on submit page.

![date](https://user-images.githubusercontent.com/35419531/56413814-5912ac80-62a6-11e9-98c4-841fd6a5a1ec.png)

**Comment by pearlpatel** [comment]
This is happen due to  #70 bug.

This will happen wen you add random number or anything manually in the input box of the date picker then it will try to convert date as date format.

This will fail and store date as 1970-01-01 in this case if user wants to set restriction then they have to override template file for date field to theme side and add readyonly="true" inside date input.

This will make more sense instead of setting default restriction form plugin.
