### ISSUE TITLE
Elementor - not getting warning/success notice.

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#899]
Go to elementor "single event field" element.
add registration filed.
there is no warning/success notice after success/fail registration form.

**Comment by mistry-jignesh** [comment]
I have performed mention steps but warning/success notice after success/fail message is not display registration form.

**Comment by lllopo** [comment]
This is still a big problem. We are building a custom single event page with Elementor (mostly because we want to get rid of the huge banner ugliness, but not only), but it with it there are no notifications of any kind shown with  registration. Not only when the user registers, but also the "you are already subscribed" message is missing. You definitely have to sort this out.

**Comment by lllopo** [comment]
@mistry-jignesh Actually, I'd rather say you better the keep the button visible but disabled for users that had already subscribed and add a notice (that works) for two reasons :
1. It is more informative for the user
2. Keeping the same elements visible in all cases makes the layout more stable. In the current situation, the designer of the Elementor page should take in consideration that the button is sometimes visible, sometimes - not. 

In all cases - do something as currently it is simply not working - no notification is shown to the subscribed user with Elementor custom templates.

**Comment by mistry-jignesh** [comment]
We have open the new enhacement for this issue. 

Issue id is - https://github.com/wpeventmanager/wp-event-manager/issues/1241

Assigned this enhacement for the developer team.
