### ISSUE TITLE
page is not creating after reinstallation of plugin 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager#930]
Go to Event manager >> Settings >> General.
Check the box adjacent to Delete Data On uninstall.
Click Save Changes.
here, plugin related some pages are not deleting.

![Screenshot_13](https://user-images.githubusercontent.com/86232676/148038013-2613d0e7-c89d-40f4-8693-aaeab45bf50e.jpg)

reinstall the core plugin , here plugin related setup steps are not displaying , and also plugin related new pages are not creating.
![Screenshot_14](https://user-images.githubusercontent.com/86232676/148038362-596392e9-73be-487b-9bf2-1661edc2430d.jpg)

**Comment by mistry-jignesh** [comment]
I have verified issue. Right now below issue is fixed .

 Plugin related new pages are not creating.

Still face below issues.

First issue - Here, plugin related some pages are not deleting.

**This issue is not fixed.** - Pages are not deleting.

Second Issue - Reinstall the core plugin , here plugin related setup steps are not displaying

**This issue is not fixed.** - Setup steps are not displaing.

**Comment by mistry-jignesh** [comment]
I have verified issue. Now this issue is fixed.

Page is not deleting issue is fixed.

So I closed the issue.
